[package]
name = "userland-execve"
version = "0.1.0"
edition = "2021"
description = "An implementation of execve() in user space"
readme = "README.md"
license = "MIT"

[dependencies.goblin]
version = "0.7.1"
default-features = false
features = ["elf32", "elf64", "endian_fd"]

[dependencies.nix]
version = "0.26.2"
default-features = false
features = ["mman", "feature", "user"]
