[package]
name = "userland-execve-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elfloader = "0.16.0"
nix = { version = "0.26.2", features = ["mman"] }
rand = "0.8.5"
xmas-elf = "0.9.0"
